stages:
  - build

# determine conan recipe string from CI_COMMIT_TAG
create_variables:
  stage: .pre
  variables:
    # safe default variables here
    CONAN_RECIPE_NAME:    $CI_PROJECT_NAME
    CONAN_RECIPE_VERSION: $CI_COMMIT_SHORT_SHA
    CONAN_RECIPE_USER:    $CI_PROJECT_NAMESPACE+$CI_PROJECT_NAME
    CONAN_RECIPE_CHANNEL: 2.16.4
  script:
    - |
      # if this is a tagged pipeline and a '-' is found in the tag ...
      if [[ "$CI_COMMIT_TAG" =~ "-" ]]; then
        # package version is first part before the '-'
        CONAN_RECIPE_VERSION="${CI_COMMIT_TAG%-*}"
        # karabo version is second part after the '-'
        CONAN_RECIPE_CHANNEL="${CI_COMMIT_TAG#*-}"
        KARABO_TAG=$CONAN_RECIPE_CHANNEL
      fi
      # pass environment variables on to next step via artifacts:reports:dotenv
      echo "CONAN_RECIPE_NAME=$CONAN_RECIPE_NAME" >> dotenv.txt
      echo "CONAN_RECIPE_VERSION=$CONAN_RECIPE_VERSION" >> dotenv.txt
      echo "CONAN_RECIPE_USER=$CONAN_RECIPE_USER" >> dotenv.txt
      echo "CONAN_RECIPE_CHANNEL=$CONAN_RECIPE_CHANNEL" >> dotenv.txt
      echo "CONAN_RECIPE=$CONAN_RECIPE_NAME/$CONAN_RECIPE_VERSION@$CONAN_RECIPE_USER/$CONAN_RECIPE_CHANNEL" >> dotenv.txt
      # dump variables to CI output
      cat dotenv.txt
  artifacts:
    reports:
      dotenv: dotenv.txt

# build template
.build_template: &build_it
  stage: build
  variables:
    KARABO_TAG:          $CONAN_RECIPE_CHANNEL
    KARABO_BROKER_TOPIC: "gitlab_ci_$CI_JOB_ID"
  script:
    # setup conan build profile
    - conan profile new default --detect || true > /dev/null
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    # setup conan and add XFEL gitlab package registry
    - conan remote add gitlab $CI_API_V4_URL/packages/conan
    - conan user -p $CI_JOB_TOKEN --remote=gitlab gitlab-ci-token
    # install karabo framework from conan package
    - conan install karaboFramework/$KARABO_TAG@karaboDevices+depends/any --install-folder $HOME/karabo --remote=gitlab > /dev/null
    - source $HOME/karabo/activate
    - pushd $CI_PROJECT_DIR
    # commands for conan to collect dependencies and build a karabo device
    - mkdir build && cd build
    - conan install .. --remote=gitlab -pr:b=default
    - conan build ..
    # push compiled karabo device package back to gitlab registry
    - conan export-pkg .. $CONAN_RECIPE
    - conan upload $CONAN_RECIPE --all --remote=gitlab --confirm
  only:
    - branches
  except:
    - master

##### confirm the projects builds #####
build:x86_64-ubuntu:
  image: conanio/gcc9:1.59.0
  <<: *build_it

# test:ubuntu20:
#   image: europeanxfel/karabo-ci:ubuntu-20
#   <<: *test_build

# test:centos7:
#   image: conanio/gcc72
#   <<: *test_build
